apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: external-net-test
  labels:
    app: external-net-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: external-net-test
  template:
    metadata:
      labels:
        app: external-net-test
    spec:
      containers:
        - name: external-net-test
          image: zvfvrv/net-test:devpython
          volumeMounts:
          - name: scripts
            mountPath: /vagrant/ext/kites/scripts/linux/
          - name: pod-shared
            mountPath: /vagrant/ext/kites/pod-shared/
          securityContext:
            privileged: true
          ports:
            - containerPort: 5201
          args: ["-s"]
      volumes:
      - name: scripts
        hostPath:
         path: /vagrant/ext/kites/scripts/linux/
      - name: pod-shared
        hostPath:
         path: /vagrant/ext/kites/pod-shared/
