apiVersion: v1
kind: Service
metadata:
  name: service-net-test
spec:
  ports:
  - name: iperf-tcp
    port: 5201
    protocol: TCP
    targetPort: 5201
  - name: iperf-udp
    port: 5201
    protocol: UDP
    targetPort: 5201
    nodePort: 5201
  selector:
    app: net-test-server
  type: NodePort